### ISSUE TITLE
Footer overlapping with body

### ISSUE THREAD

**Issue by AnirudhPanda** [AkhileshThite/COVID-19-VaccineFinder#14]

**Comment by akhileshthite** [comment]
@AnirudhPanda
Thank you for noticing this issue. Yes, on some smartphone screens the footer is overlapping with body.
Would you like to work on this issue?

**Comment by AnirudhPanda** [comment]
Yeah I can, also horizontal scrolling needs to be fixed

**Comment by akhileshthite** [comment]
> Yeah I can, also horizontal scrolling needs to be fixed

Okay, assigned.

**Comment by AnirudhPanda** [comment]
Hey @AkhileshThite I am not able to connect to http://0.0.0.0:8080/ after I did `python app.py`
Showing on the web : This site can’t be reached, The webpage at http://0.0.0.0:8080/ might be temporarily down or it may have moved permanently to a new web address.
![Capture](https://user-images.githubusercontent.com/66218496/123664782-49635b00-d855-11eb-9d59-88db4304b7b5.PNG)

**Comment by akhileshthite** [comment]
> Hey @AkhileshThite I am not able to connect to http://0.0.0.0:8080/ after I did `python app.py`
> Showing on the web : This site can’t be reached, The webpage at http://0.0.0.0:8080/ might be temporarily down or it may have moved permanently to a new web address.
> ![Capture](https://user-images.githubusercontent.com/66218496/123664782-49635b00-d855-11eb-9d59-88db4304b7b5.PNG)

Okay, then try default Flask server 👉 `app.run(debug=True)`
I set that because I'm deploying on AWS EC2 instance.

**Comment by AnirudhPanda** [comment]
> > Hey @AkhileshThite I am not able to connect to http://0.0.0.0:8080/ after I did `python app.py`
> > Showing on the web : This site can’t be reached, The webpage at http://0.0.0.0:8080/ might be temporarily down or it may have moved permanently to a new web address.
> > ![Capture](https://user-images.githubusercontent.com/66218496/123664782-49635b00-d855-11eb-9d59-88db4304b7b5.PNG)
> 
> Okay, then try default Flask server 👉 `app.run(debug=True)`
> I set that because I'm deploying on AWS EC2 instance.

`$ app.run(debug=True)`

bash: syntax error near unexpected token `debug=True'

**Comment by akhileshthite** [comment]
> > > Hey @AkhileshThite I am not able to connect to http://0.0.0.0:8080/ after I did `python app.py`
> > > Showing on the web : This site can’t be reached, The webpage at http://0.0.0.0:8080/ might be temporarily down or it may have moved permanently to a new web address.
> > > ![Capture](https://user-images.githubusercontent.com/66218496/123664782-49635b00-d855-11eb-9d59-88db4304b7b5.PNG)
> > 
> > 
> > Okay, then try default Flask server 👉 `app.run(debug=True)`
> > I set that because I'm deploying on AWS EC2 instance.
> 
> `$ app.run(debug=True)`
> 
> bash: syntax error near unexpected token `debug=True'

Try `python3 app.py`

**Comment by akhileshthite** [comment]
@AnirudhPanda Is it working now?

**Comment by AnirudhPanda** [comment]
Not working for me

**Comment by AnirudhPanda** [comment]
Okay @AkhileshThite it worked on http://localhost:8080/

**Comment by akhileshthite** [comment]
> Not working for me

Sir, It should work. 
-> Check your python version by `python --version` command, you should use Python version 3, because of f-string syntax for API.
-> Check indentation after this `app.run(debug=True)` change , try to run the app.py file in IDE instead of terminal.

**Comment by akhileshthite** [comment]
> Okay @AkhileshThite it worked on http://localhost:8080/

Okay, great.

**Comment by akhileshthite** [comment]
> Okay @AkhileshThite it worked on http://localhost:8080/

I'll make the necessary changes in main README.md, so that it should work for all contributors later without any problem.

**Comment by AnirudhPanda** [comment]
> > Okay @AkhileshThite it worked on http://localhost:8080/
> 
> I'll make the necessary changes in main README.md, so that it should work for all contributors later without any problem.

there is still an issue of live reloading though.

**Comment by AnirudhPanda** [comment]
#15 Check it once and update me

**Comment by akhileshthite** [comment]
> #15 Check it once and update me

Yes.
