### ISSUE TITLE
Add alert popup if the sessions are zero/empty.

### ISSUE THREAD

**Issue by akhileshthite** [AkhileshThite/COVID-19-VaccineFinder#16]
### **Is your feature request related to a problem? Please describe.**
-> After submitting PIN & DATE if the sessions are empty then it displays nothing on the screen, check out the SS given below.

![Screenshot 2021-07-17 at 8 36 05 PM](https://user-images.githubusercontent.com/68826419/126041278-b48beb65-1123-494f-b6e7-2ca7505a962b.png)

Row API json output: 

![Screenshot 2021-07-17 at 8 36 48 PM](https://user-images.githubusercontent.com/68826419/126041281-e238860f-c1e5-4fd3-91dd-d1fc0af11ea5.png)

### **Describe the solution you'd like...**
-> Add simple alert popup saying "Sessions are currently unavailable, please try again after some time."  if the sessions are zero/empty.

### **Approach to be followed:**
-> Main code file is `app.py`,
eg:- ```if response['sessions'] == 0:
                     flash("Alert message here.")```
OR
-> You can try it using JavaScript,`/static/main.js`
-> **Running of the project, git commands & all other information is given in the [README.md](https://github.com/AkhileshThite/COVID-19-VaccineFinder) of the project.**

**Comment by tanvi355** [comment]
Can I please try doing this? @AkhileshThite

**Comment by akhileshthite** [comment]
> Can I please try doing this? @AkhileshThite

Yes! assigned.
