### ISSUE TITLE
Issue & PR Templates

### ISSUE THREAD

**Issue by akhileshthite** [AkhileshThite/COVID-19-VaccineFinder#2]
Add Issue & PR Templates.

**Comment by prathimacode-hub** [comment]
Can I work on this issue? @AkhileshThite

**Comment by akhileshthite** [comment]
> Can I work on this issue? @AkhileshThite

Yes :)

**Comment by prathimacode-hub** [comment]
> > Can I work on this issue? @AkhileshThite
> 
> Yes :)

I feel it's better, if configuration file is as well added to welcome contributors. Can I add that as well, if you're interested? @AkhileshThite

**Comment by akhileshthite** [comment]
> > > Can I work on this issue? @AkhileshThite
> > 
> > 
> > Yes :)
> 
> I feel it's better, if configuration file is as well added to welcome contributors. Can I add that as well, if you're interested? @AkhileshThite

Okay great! add it.

**Comment by prathimacode-hub** [comment]
I had created a PR for the same. Kindly check through it. @AkhileshThite
